"""
Offline Pattern Memory Desk.

Reads trade reviews generated by the Trade Review Lab, aggregates recurring
signals of success and failure, and produces a structured pattern library.

Usage:
    python pattern_memory_desk.py --system agent
    python pattern_memory_desk.py --system all --no-claude
    python pattern_memory_desk.py --system pump --limit 50 --stdout
    python pattern_memory_desk.py --system scalping --min-occurrences 3
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
from collections import Counter
from datetime import datetime
from pathlib import Path


# ── LOCAL RUNTIME RESOLUTION (side-effect-free) ──────────────────────────────
_APP_DIR = Path(__file__).resolve().parent


def _slugify(value: str) -> str:
    normalized = re.sub(r"[^a-zA-Z0-9._-]+", "-", value.strip())
    return normalized.strip("-._").lower() or "baseline"


BOT_ID = _slugify(os.getenv("BOT_ID", "baseline"))
_RUNTIME_BASE = Path(os.getenv("BOT_RUNTIME_BASE_DIR", str(_APP_DIR / "runtime")))
RUNTIME_DIR = _RUNTIME_BASE / BOT_ID
REVIEWS_DIR = RUNTIME_DIR / "trade_reviews"

VALID_SYSTEMS = {"paper", "agent", "pump", "scalping", "all"}

_DEFAULT_MIN_OCCURRENCES = 2


# ── REVIEW DISCOVERY ─────────────────────────────────────────────────────────

def _discover_reviews(
    system: str, limit: int = 0,
) -> tuple[list[dict], dict]:
    """Find and load trade_review_report.json files.

    Filters by system prefix in the directory name. Returns a tuple of
    (valid_reviews, scan_stats) where scan_stats tracks how many were
    scanned, skipped as stubs, skipped as invalid, and used.
    """
    stats = {
        "reviews_scanned": 0,
        "reviews_stub_skipped": 0,
        "reviews_invalid_skipped": 0,
        "reviews_used": 0,
    }

    if not REVIEWS_DIR.exists():
        return [], stats

    review_dirs = sorted(REVIEWS_DIR.iterdir(), reverse=True)

    loaded: list[dict] = []
    for d in review_dirs:
        if not d.is_dir():
            continue

        # Filter by system prefix (e.g. "agent-1-...")
        dir_name = d.name
        if system != "all":
            if not dir_name.startswith(f"{system}-"):
                continue

        report_file = d / "trade_review_report.json"
        if not report_file.exists():
            continue

        stats["reviews_scanned"] += 1

        try:
            data = json.loads(report_file.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            stats["reviews_invalid_skipped"] += 1
            continue

        # Skip stubs (context_only) — they have no review content
        if data.get("status") == "context_only":
            stats["reviews_stub_skipped"] += 1
            continue

        # Must have trade_identity to be usable
        if "trade_identity" not in data:
            stats["reviews_invalid_skipped"] += 1
            continue

        # Tag with source directory for traceability
        data["_source_dir"] = str(d)
        loaded.append(data)

        if 0 < limit <= len(loaded):
            break

    stats["reviews_used"] = len(loaded)
    return loaded, stats


# ── DETERMINISTIC AGGREGATION ────────────────────────────────────────────────

def _normalize_text(text: str) -> str:
    """Normalize a string for frequency counting."""
    return re.sub(r"\s+", " ", text.strip().lower())


def _count_items(reviews: list[dict], field: str) -> Counter:
    """Count distinct reviews containing each normalized item.

    Each review contributes at most 1 to each item's count, even if the
    item appears multiple times within that review.
    """
    counter: Counter = Counter()
    for r in reviews:
        items = r.get(field, [])
        if not isinstance(items, list):
            continue
        seen_in_review: set[str] = set()
        for item in items:
            if isinstance(item, str) and item.strip():
                seen_in_review.add(_normalize_text(item))
        for key in seen_in_review:
            counter[key] += 1
    return counter


def _count_items_with_evidence(
    reviews: list[dict], field: str,
) -> tuple[Counter, dict[str, dict]]:
    """Count distinct reviews per item and track per-item evidence.

    Each review contributes at most 1 to each item's count, even if the
    item appears multiple times within that review. evidence_map tracks
    which systems and symbols sustain each item.

    Returns (counter, evidence_map).
    """
    counter: Counter = Counter()
    evidence: dict[str, dict] = {}

    for r in reviews:
        items = r.get(field, [])
        if not isinstance(items, list):
            continue

        identity = r.get("trade_identity", {})
        r_system = identity.get("system", "")
        r_symbol = identity.get("symbol", "")

        # Deduplicate within this review
        seen_in_review: set[str] = set()
        for item in items:
            if isinstance(item, str) and item.strip():
                seen_in_review.add(_normalize_text(item))

        for key in seen_in_review:
            counter[key] += 1
            if key not in evidence:
                evidence[key] = {"systems": set(), "symbols": set()}
            if r_system:
                evidence[key]["systems"].add(r_system)
            if r_symbol and r_symbol != "?":
                evidence[key]["symbols"].add(r_symbol)

    return counter, evidence


def _aggregate_deterministic(reviews: list[dict], min_occurrences: int) -> dict:
    """Build deterministic aggregation from reviews without LLM."""

    # Classifications
    class_counter: Counter = Counter()
    for r in reviews:
        c = r.get("classification", "unclear")
        class_counter[c] += 1

    # Field counters (with per-item evidence for candidates)
    root_causes, root_causes_ev = _count_items_with_evidence(reviews, "root_causes")
    mistakes, mistakes_ev = _count_items_with_evidence(reviews, "mistakes")
    things_done_well, tdw_ev = _count_items_with_evidence(reviews, "things_done_well")
    tags = _count_items(reviews, "tags")

    # Lessons
    lesson_counter: Counter = Counter()
    for r in reviews:
        lesson = r.get("lesson", "")
        if isinstance(lesson, str) and lesson.strip():
            lesson_counter[_normalize_text(lesson)] += 1

    # Counterfactuals — plausible ones only
    cf_counter: Counter = Counter()
    for r in reviews:
        cfs = r.get("counterfactuals", [])
        if isinstance(cfs, list):
            for cf in cfs:
                if isinstance(cf, dict) and cf.get("plausible_at_the_time"):
                    scenario = cf.get("scenario", "unclear")
                    cf_counter[_normalize_text(scenario)] += 1

    # Collect systems and symbols
    systems_seen: set[str] = set()
    symbols_seen: set[str] = set()
    for r in reviews:
        identity = r.get("trade_identity", {})
        s = identity.get("system", "")
        if s:
            systems_seen.add(s)
        sym = identity.get("symbol", "")
        if sym and sym != "?":
            symbols_seen.add(sym)

    # Build summary (top items)
    summary = {
        "top_classifications": class_counter.most_common(5),
        "top_root_causes": root_causes.most_common(10),
        "top_mistakes": mistakes.most_common(10),
        "top_things_done_well": things_done_well.most_common(10),
        "top_tags": tags.most_common(10),
        "top_lessons": lesson_counter.most_common(5),
        "top_counterfactual_scenarios": cf_counter.most_common(5),
    }

    # Build pattern candidates from recurring signals (with per-item evidence)
    pattern_candidates = _build_pattern_candidates(
        root_causes, root_causes_ev,
        mistakes, mistakes_ev,
        things_done_well, tdw_ev,
        min_occurrences,
    )

    return {
        "summary": summary,
        "pattern_candidates": pattern_candidates,
        "systems": sorted(systems_seen),
        "symbols": sorted(symbols_seen),
    }


def _pattern_id(kind: str, signal: str) -> str:
    """Generate a stable short ID for a pattern."""
    raw = f"{kind}:{signal}"
    return hashlib.sha256(raw.encode()).hexdigest()[:12]


def _build_pattern_candidates(
    root_causes: Counter,
    root_causes_ev: dict[str, dict],
    mistakes: Counter,
    mistakes_ev: dict[str, dict],
    things_done_well: Counter,
    tdw_ev: dict[str, dict],
    min_occurrences: int,
) -> list[dict]:
    """Promote recurring signals to pattern candidates.

    Each candidate carries only the systems/symbols from its own evidence,
    not the global set.
    """
    candidates: list[dict] = []

    def _make_candidate(
        signal: str, count: int, kind: str, source_field: str,
        ev_map: dict[str, dict],
    ) -> dict:
        ev = ev_map.get(signal, {"systems": set(), "symbols": set()})
        return {
            "pattern_id": _pattern_id(source_field, signal),
            "title": signal,
            "kind": kind,
            "source_field": source_field,
            "evidence_count": count,
            "systems": sorted(ev["systems"]),
            "symbols": sorted(ev["symbols"]),
            "signals": [signal],
            "lesson": "",
            "actionability": "high" if count >= min_occurrences * 2 else "medium",
        }

    # Negative patterns from mistakes
    for signal, count in mistakes.most_common(20):
        if count < min_occurrences:
            continue
        candidates.append(_make_candidate(signal, count, "negative", "mistakes", mistakes_ev))

    # Negative patterns from root causes
    for signal, count in root_causes.most_common(20):
        if count < min_occurrences:
            continue
        candidates.append(_make_candidate(signal, count, "negative", "root_causes", root_causes_ev))

    # Positive patterns from things done well
    for signal, count in things_done_well.most_common(20):
        if count < min_occurrences:
            continue
        candidates.append(_make_candidate(signal, count, "positive", "things_done_well", tdw_ev))

    # Sort by evidence count descending
    candidates.sort(key=lambda c: c["evidence_count"], reverse=True)
    return candidates


# ── CLAUDE SYNTHESIS (optional) ──────────────────────────────────────────────

_SYNTHESIS_PROMPT = """Voce e um analista de trading quantitativo revisando padroes extraidos de reviews de trades.

Receba os dados agregados abaixo e produza:
1. Padroes nomeados com titulos curtos e claros
2. Recomendacoes praticas (max 5)
3. Avaliacao honesta de confianca

REGRAS:
- Nao invente dados que nao estao nos agregados
- Se a amostra for pequena, diga isso
- Diferencie padrao forte (muitas ocorrencias) de sinal fraco (poucas)
- Recomendacoes devem ser acionaveis e conservadoras

Responda SOMENTE com JSON valido:
{
  "named_patterns": [
    {
      "name": "nome curto",
      "kind": "positive|negative|mixed",
      "description": "descricao curta",
      "confidence": "high|medium|low",
      "recommendation": "acao sugerida"
    }
  ],
  "recommendations": ["acao 1", "acao 2"],
  "sample_size_assessment": "sufficient|marginal|insufficient"
}"""


def _call_claude_synthesis(aggregation: dict, reviews_count: int) -> dict | None:
    """Optional Claude synthesis of aggregated patterns."""
    api_key = os.getenv("ANTHROPIC_API_KEY")
    if not api_key:
        return None

    try:
        from anthropic import Anthropic
        client = Anthropic(api_key=api_key)

        # Build a compact data payload (no raw reviews, just aggregates)
        payload = {
            "reviews_analyzed": reviews_count,
            "summary": aggregation["summary"],
            "pattern_candidates_count": len(aggregation["pattern_candidates"]),
            "top_patterns": aggregation["pattern_candidates"][:10],
            "systems": aggregation["systems"],
            "symbols": aggregation["symbols"],
        }

        data_text = json.dumps(payload, ensure_ascii=False, indent=2, default=str)

        response = client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=1024,
            system=_SYNTHESIS_PROMPT,
            messages=[{"role": "user", "content": data_text}],
        )

        text = response.content[0].text.strip()
        if text.startswith("```"):
            lines = text.split("\n")
            json_lines = []
            inside = False
            for line in lines:
                if line.startswith("```") and not inside:
                    inside = True
                    continue
                elif line.startswith("```") and inside:
                    break
                elif inside:
                    json_lines.append(line)
            text = "\n".join(json_lines)

        raw = json.loads(text)
        return _normalize_synthesis(raw)
    except Exception as exc:
        print(f"  [PATTERN] Claude synthesis failed: {exc}")
        return None


def _normalize_synthesis(raw) -> dict:
    """Normalize Claude's synthesis response."""
    if not isinstance(raw, dict):
        raw = {}

    named_patterns = raw.get("named_patterns", [])
    if not isinstance(named_patterns, list):
        named_patterns = []
    named_patterns = named_patterns[:10]
    for p in named_patterns:
        if not isinstance(p, dict):
            continue
        p.setdefault("name", "unnamed")
        p.setdefault("kind", "mixed")
        p.setdefault("description", "")
        p.setdefault("confidence", "low")
        p.setdefault("recommendation", "")

    recommendations = raw.get("recommendations", [])
    if not isinstance(recommendations, list):
        recommendations = []
    recommendations = [str(r) for r in recommendations[:5] if r]

    assessment = raw.get("sample_size_assessment", "insufficient")
    if assessment not in ("sufficient", "marginal", "insufficient"):
        assessment = "insufficient"

    return {
        "named_patterns": [p for p in named_patterns if isinstance(p, dict)],
        "recommendations": recommendations,
        "sample_size_assessment": assessment,
    }


# ── OUTPUT GENERATION ────────────────────────────────────────────────────────

def _build_report_json(
    system: str,
    reviews: list[dict],
    aggregation: dict,
    synthesis: dict | None,
    scan_stats: dict | None = None,
) -> dict:
    """Build the final pattern memory report."""
    ss = scan_stats or {}
    report = {
        "generated_at": datetime.now().isoformat(),
        "source": {
            "system": system,
            "reviews_scanned": ss.get("reviews_scanned", len(reviews)),
            "reviews_stub_skipped": ss.get("reviews_stub_skipped", 0),
            "reviews_invalid_skipped": ss.get("reviews_invalid_skipped", 0),
            "reviews_used": ss.get("reviews_used", len(reviews)),
            "systems": aggregation["systems"],
            "symbols": aggregation["symbols"],
        },
        "summary": {
            k: [[item, count] for item, count in v]
            for k, v in aggregation["summary"].items()
        },
        "pattern_candidates": aggregation["pattern_candidates"],
    }

    if synthesis:
        report["claude_synthesis"] = synthesis
        report["recommendations"] = synthesis.get("recommendations", [])
    else:
        report["recommendations"] = []

    return report


def _build_report_markdown(report: dict) -> str:
    """Generate a human-readable Markdown report."""
    lines: list[str] = []
    source = report["source"]
    summary = report["summary"]

    lines.append("# Pattern Memory Report")
    lines.append("")
    lines.append(f"Generated: {report['generated_at']}")
    lines.append("")

    # Executive summary
    lines.append("## Resumo Executivo")
    lines.append("")
    lines.append(f"- Sistema: {source['system']}")
    lines.append(f"- Reviews escaneados: {source['reviews_scanned']}")
    stubs = source.get('reviews_stub_skipped', 0)
    invalid = source.get('reviews_invalid_skipped', 0)
    if stubs or invalid:
        lines.append(f"- Descartados: {stubs} stubs, {invalid} invalidos")
    lines.append(f"- Reviews usados: {source['reviews_used']}")
    lines.append(f"- Sistemas cobertos: {', '.join(source.get('systems', [])) or 'nenhum'}")
    lines.append(f"- Simbolos cobertos: {', '.join(source.get('symbols', [])) or 'nenhum'}")
    lines.append("")

    if source["reviews_used"] == 0:
        lines.append("**Nenhum review valido encontrado. Base vazia.**")
        lines.append("")
        return "\n".join(lines)

    if source["reviews_used"] < 5:
        lines.append(
            f"**Atencao: amostra pequena ({source['reviews_used']} reviews usados). "
            f"Padroes abaixo devem ser tratados com cautela.**"
        )
        lines.append("")

    # Classifications
    _add_counter_section(lines, "Classificacoes", summary.get("top_classifications", []))

    # Errors
    _add_counter_section(lines, "Principais Erros Recorrentes", summary.get("top_mistakes", []))

    # Root causes
    _add_counter_section(lines, "Causas Raiz Frequentes", summary.get("top_root_causes", []))

    # Strengths
    _add_counter_section(lines, "Principais Acertos Recorrentes", summary.get("top_things_done_well", []))

    # Tags
    _add_counter_section(lines, "Tags Frequentes", summary.get("top_tags", []))

    # Lessons
    _add_counter_section(lines, "Licoes Recorrentes", summary.get("top_lessons", []))

    # Pattern candidates
    candidates = report.get("pattern_candidates", [])
    if candidates:
        lines.append("## Pattern Candidates")
        lines.append("")
        for c in candidates:
            kind_label = {"positive": "+", "negative": "-", "mixed": "~"}.get(c["kind"], "?")
            lines.append(
                f"- [{kind_label}] **{c['title']}** "
                f"(x{c['evidence_count']}, {c['actionability']}, "
                f"source: {c.get('source_field', '?')})"
            )
        lines.append("")

    # Claude synthesis
    synthesis = report.get("claude_synthesis")
    if synthesis:
        lines.append("## Sintese Claude")
        lines.append("")
        lines.append(f"Avaliacao da amostra: **{synthesis.get('sample_size_assessment', '?')}**")
        lines.append("")
        named = synthesis.get("named_patterns", [])
        if named:
            for p in named:
                lines.append(
                    f"- **{p.get('name', '?')}** ({p.get('kind', '?')}, "
                    f"conf={p.get('confidence', '?')}): "
                    f"{p.get('description', '')}"
                )
                if p.get("recommendation"):
                    lines.append(f"  - Acao: {p['recommendation']}")
            lines.append("")

    # Recommendations
    recs = report.get("recommendations", [])
    if recs:
        lines.append("## Acoes Sugeridas")
        lines.append("")
        for r in recs:
            lines.append(f"- {r}")
        lines.append("")

    # Limitations
    lines.append("## Limitacoes")
    lines.append("")
    if source["reviews_used"] < 10:
        lines.append("- Amostra pequena: padroes podem ser ruido")
    if not synthesis:
        lines.append("- Sem sintese Claude: apenas agregacao deterministica")
    lines.append("- Padroes sao candidatos, nao regras validadas")
    lines.append("- Nenhuma mudanca foi aplicada automaticamente no bot")
    lines.append("")

    return "\n".join(lines)


def _add_counter_section(lines: list[str], title: str, items: list) -> None:
    """Add a counter-based section to the markdown."""
    lines.append(f"## {title}")
    lines.append("")
    if not items:
        lines.append("Nenhum item encontrado.")
    else:
        for item in items:
            if isinstance(item, (list, tuple)) and len(item) == 2:
                lines.append(f"- {item[0]} (x{item[1]})")
            else:
                lines.append(f"- {item}")
    lines.append("")


def _save_outputs(report: dict, md_content: str, output_dir: str,
                  prompt_text: str | None = None) -> dict:
    """Save all output files."""
    Path(output_dir).mkdir(parents=True, exist_ok=True)
    files: dict[str, str] = {}

    report_json_path = str(Path(output_dir) / "pattern_memory_report.json")
    Path(report_json_path).write_text(
        json.dumps(report, ensure_ascii=False, indent=2, default=str),
        encoding="utf-8",
    )
    files["report_json"] = report_json_path

    report_md_path = str(Path(output_dir) / "pattern_memory_report.md")
    Path(report_md_path).write_text(md_content, encoding="utf-8")
    files["report_md"] = report_md_path

    if prompt_text:
        prompt_path = str(Path(output_dir) / "pattern_memory_prompt.md")
        Path(prompt_path).write_text(prompt_text, encoding="utf-8")
        files["prompt_md"] = prompt_path

    return files


# ── MAIN RUNNER ──────────────────────────────────────────────────────────────

def run_pattern_memory(
    system: str,
    limit: int = 0,
    use_claude: bool = True,
    min_occurrences: int = _DEFAULT_MIN_OCCURRENCES,
    output_dir: str | None = None,
) -> dict:
    """Run the pattern memory desk.

    Returns result dict with report, files, and metadata.
    """
    if system not in VALID_SYSTEMS:
        raise ValueError(f"Sistema invalido: {system}. Use: {sorted(VALID_SYSTEMS)}")

    if min_occurrences < 2:
        raise ValueError(
            f"min_occurrences deve ser >= 2 para evitar promover ruido "
            f"(recebido: {min_occurrences})"
        )

    # Discover reviews
    reviews, scan_stats = _discover_reviews(system, limit=limit)
    print(
        f"  [PATTERN] Escaneados: {scan_stats['reviews_scanned']} | "
        f"Stubs: {scan_stats['reviews_stub_skipped']} | "
        f"Invalidos: {scan_stats['reviews_invalid_skipped']} | "
        f"Usados: {scan_stats['reviews_used']} (system={system})"
    )

    # Aggregate deterministically
    aggregation = _aggregate_deterministic(reviews, min_occurrences)

    # Optional Claude synthesis
    synthesis = None
    if use_claude and reviews:
        print("  [PATTERN] Chamando Claude para sintese...")
        synthesis = _call_claude_synthesis(aggregation, len(reviews))
        if synthesis:
            print("  [PATTERN] Sintese recebida.")
        else:
            print("  [PATTERN] Claude indisponivel. Usando apenas agregacao deterministica.")
    elif not use_claude:
        print("  [PATTERN] Claude desligado. Usando apenas agregacao deterministica.")

    # Build report
    report = _build_report_json(system, reviews, aggregation, synthesis, scan_stats)
    md_content = _build_report_markdown(report)

    # Output directory
    ts_slug = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    if output_dir is None:
        output_dir = str(RUNTIME_DIR / "pattern_memory" / f"{system}-{ts_slug}")

    files = _save_outputs(report, md_content, output_dir)

    return {
        "system": system,
        "reviews_found": len(reviews),
        "pattern_candidates": len(report.get("pattern_candidates", [])),
        "has_synthesis": synthesis is not None,
        "report": report,
        "files": files,
    }


# ── CLI ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Offline Pattern Memory Desk — agrega padroes de trade reviews",
    )
    parser.add_argument(
        "--system", required=True,
        choices=["paper", "agent", "pump", "scalping", "all"],
        help="Sistema de trading (obrigatorio)",
    )
    parser.add_argument(
        "--limit", type=int, default=0,
        help="Maximo de reviews a processar (0 = todos)",
    )
    parser.add_argument(
        "--min-occurrences", type=int, default=_DEFAULT_MIN_OCCURRENCES,
        help=f"Minimo de ocorrencias para promover a pattern candidate (default: {_DEFAULT_MIN_OCCURRENCES})",
    )
    parser.add_argument(
        "--no-claude", action="store_true",
        help="Desabilitar chamada ao Claude",
    )
    parser.add_argument(
        "--stdout", action="store_true",
        help="Imprimir relatorio no stdout",
    )
    parser.add_argument(
        "--output-dir", type=str, default=None,
        help="Diretorio de saida customizado",
    )
    args = parser.parse_args()

    try:
        result = run_pattern_memory(
            system=args.system,
            limit=args.limit,
            use_claude=not args.no_claude,
            min_occurrences=args.min_occurrences,
            output_dir=args.output_dir,
        )
    except ValueError as exc:
        print(f"  [PATTERN] {exc}")
        sys.exit(1)

    print()
    src = result["report"]["source"]
    print(f"Pattern Memory: {result['system']}")
    print(f"Reviews escaneados: {src['reviews_scanned']} | usados: {src['reviews_used']}")
    print(f"Pattern candidates: {result['pattern_candidates']}")
    print(f"Sintese Claude: {'sim' if result['has_synthesis'] else 'nao'}")
    print()
    print("Arquivos gerados:")
    for label, path in result["files"].items():
        print(f"  {label}: {path}")

    if args.stdout:
        print()
        print("=" * 60)
        report_md = result["files"].get("report_md")
        if report_md and Path(report_md).exists():
            print(Path(report_md).read_text(encoding="utf-8"))


if __name__ == "__main__":
    main()
